name: Shingy
favicon: null
layout_spectrum: 0.4115740864071995
typography_spectrum: 0.5637061519082636
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.7043430344201624
  lightness: 0.3873792579397559
  saturation: 0.697530449135229
  rhythmicContrast: 0.982775550102815
purpose: []
